export const brands = {
  petflow: {
    id: "petflow",
    name: "PetFlow",
    vertical: "pet",
    resourceLabel: "Profissionais",
    customerLabel: "Tutores",
    tagline: "Mais cuidado. Menos correria.",
    description: "A agenda que acompanha o ritmo do seu banho e tosa.",
    accent: "#176451",
    initialService: "Banho e tosa",
    duration: 60,
    price: 9000,
    hasPets: true,
  },
  barberflow: {
    id: "barberflow",
    name: "BarberFlow",
    vertical: "barber",
    resourceLabel: "Barbeiros",
    customerLabel: "Clientes",
    tagline: "Sua agenda no ponto.",
    description: "Organize seus horários e dedique mais tempo a cada cliente.",
    accent: "#815a2e",
    initialService: "Corte de cabelo",
    duration: 30,
    price: 4500,
    hasPets: false,
  },
  beautyflow: {
    id: "beautyflow",
    name: "BeautyFlow",
    vertical: "beauty",
    resourceLabel: "Profissionais",
    customerLabel: "Clientes",
    tagline: "Espaço para cuidar.",
    description: "Uma rotina mais leve para o seu salão e seus clientes.",
    accent: "#915a78",
    initialService: "Corte e escova",
    duration: 60,
    price: 12000,
    hasPets: false,
  },
  esteticaflow: {
    id: "esteticaflow",
    name: "EsteticaFlow",
    vertical: "aesthetics",
    resourceLabel: "Profissionais",
    customerLabel: "Clientes",
    tagline: "Tempo para o bem-estar.",
    description: "Organize os atendimentos do seu espaço de estética.",
    accent: "#59728f",
    initialService: "Atendimento de estética",
    duration: 60,
    price: 15000,
    hasPets: false,
  },
} as const;
export type BrandId = keyof typeof brands;
export function brandById(id: string) {
  return brands[id as BrandId];
}
